name: Windows Workflow

on: [push]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run a Windows Command
      run: |
        echo "Hello, GitHub Actions!"
        dir
